version: "3.9"

services:
  express-01:
    build: ./express-01
    ports:
      - "3000:3000"
    volumes:
      - ./express-01:/app

  express-02:
    build: ./express-02
    ports:
      - "3001:3001"
    volumes:
      - ./express-02:/app
  
  db:
    image: postgres
    restart: always
    depends_on:
      - express-01
    environment:
      - POSTGRES_DB=express
      - POSTGRES_HOST=5432
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080